services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      timeout: 10s
      retries: 10
    extends:
      file: qa-config.yml
      service: network-deploy-service

  democonfigserver:
    image: "yunomix2834/democonfigserver:d1"
    container_name: democonfigserver
    ports:
      - "8091:8091"
    healthcheck:
      test: "curl --fail --silent localhost:8091/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: qa-config.yml
      service: microservice-base-config

  demoeurekaserver:
    image: "yunomix2834/demoeurekaserver:d1"
    container_name: demoeurekaserver
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: qa-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "demoeurekaserver"

  demo1:
    image: "yunomix2834/demo1:d1"
    container_name: demo1
    ports:
      - "8093:8093"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8093/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "demo1"
    extends:
      file: qa-config.yml
      service: microservice-eureka-config

  demo2:
    image: "yunomix2834/demo2:d1"
    container_name: demo2
    ports:
      - "8094:8094"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8094/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "demo2"
    extends:
      file: qa-config.yml
      service: microservice-eureka-config

  demogatewayserver:
    image: "yunomix2834/demogatewayserver:d1"
    container_name: demogatewayserver
    ports:
      - "8092:8092"
    depends_on:
      demo2:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "demogatewayserver"
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    extends:
      file: qa-config.yml
      service: microservice-eureka-config

networks:
  demo:
    driver: "bridge"